// <auto-generated />
namespace glps.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_bchn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_bchn));
        
        string IMigrationMetadata.Id
        {
            get { return "202205080655042_update_bchn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
