// <auto-generated />
namespace glps.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_asset_details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_asset_details));
        
        string IMigrationMetadata.Id
        {
            get { return "202205090817440_Update_asset_details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
