// <auto-generated />
namespace glps.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_airport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_airport));
        
        string IMigrationMetadata.Id
        {
            get { return "202205090803191_Update_airport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
